apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: group-6-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: my-container-backend
          image: nutbodyslam053/group-6-marketplace:v1.1
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8081
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: my-secret-group-6
                  key: SECRET_KEY
            - name: MYSQL_DNS
              valueFrom:
                secretKeyRef:
                  name: my-secret-group-6
                  key: MYSQL_DNS
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: group-6-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: my-container-mysql
          image: mysql
          imagePullPolicy: "IfNotPresent"
          # command:
          #   - "--default-authentication-plugin=mysql_native_password"
          # restart: always
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: example
            - name: MYSQL_DATABASE
              value: db
          ports:
            - containerPort: 3306
