apiVersion: apps/v1
kind: Deployment
metadata:
  name: kai-nuxtjs-deployment-dev
  namespace: dev
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: kai-nuxtjs-dev
  template:
    metadata:
      labels:
        app: kai-nuxtjs-dev
    spec:
      containers:
      - name: kai-nuxtjs
        image: ghcr.io/the-cloud-camp/project-demo:dev-41729da
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
