apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kai-nuxtjs-ingress-dev
  namespace: dev
  labels:
    name: kai-nuxtjs-dev
spec:
  rules:
  ingressClassName: nginx
  - host: tcc-01.th1.proen.cloud
    http:
      paths:
      - pathType: Prefix
        path: "/kai-nuxtjs-dev"
        backend:
          service:
            name: kai-nuxtjs-dev
            port: 
              number: 3000
