# apiVersion: v1
# kind: Service
# metadata:
#   creationTimestamp: null
#   labels:
#     app: tcc-2-route
#   name: tcc-2-route-service
#   namespace: group-2-dev
# spec:
#   ports:
#   - port: 8004
#     protocol: TCP
#     targetPort: 8004
#   selector:
#     app: tcc-2-route
# status:
#   loadBalancer: {}
