apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: tcc-2-permission
  name: tcc-2-permission-service
  namespace: group-2-dev
spec:
  ports:
  - port: 8005
    protocol: TCP
    targetPort: 8005
  selector:
    app: tcc-2-permission
status:
  loadBalancer: {}
