apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: tcc-2-token
  name: tcc-2-token-service
  namespace: group-2-dev
spec:
  ports:
  - port: 8002
    protocol: TCP
    targetPort: 8002
  selector:
    app: tcc-2-token
status:
  loadBalancer: {}
