apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-group-6
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app-group-6
  template:
    metadata:
      labels:
        app: my-app-group-6
    spec:
      containers:
        - name: my-container-group-6
          image: nutbodyslam053/rust:latest
          imagePullPolicy: "IfNotPresent"
          ports:
          - containerPort: 8080

        #   envFrom:
        # - secretRef:
        #   name: my-secret
        # - configMapRef:
        #   name: my-configmap
