apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment-group-6
  namespace: group-6-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-group-6
  template:
    metadata:
      labels:
        app: my-app-group-6
    spec:
      containers:
        - name: my-container-group-6
          image: nutbodyslam053/group-6-marketplace:v1
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8081
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: my-secret-group-6
                  key: SECRET_KEY
            - name: MYSQL_DNS
              valueFrom:
                secretKeyRef:
                  name: my-secret-group-6
                  key: MYSQL_DNS
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-db-deployment-group-6
  namespace: group-6-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-db-group-6
  template:
    metadata:
      labels:
        app: my-db-group-6
    spec:
      containers:
        - name: mysql
          image: mysql
          imagePullPolicy: "IfNotPresent"
          # command:
          #   - "--default-authentication-plugin=mysql_native_password"
          # restart: always
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: example
            - name: MYSQL_DATABASE
              value: db
          ports:
            - containerPort: 3306
