apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shobteeprajump-ingress
  namespace: group-4-dev
  labels:
    name: shobteeprajump-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: tcc-01.th1.proen.cloud
    http:
      paths:
      - pathType: Prefix
        path: "/group-4-dev/app"
        backend:
          service:
            name: shobteeprajump-service
            port: 
              number: 3000
      - pathType: Prefix
        path: "/group-4-dev/ticket"
        backend:
          service:
            name: shobteeprajump-producer-service
            port: 
              number: 8003

