apiVersion: v1
kind: Secret
metadata:
  name: my-secret-group-6
  namespace: group-6-dev
type: Opaque
data:
  MYSQL_DNS: cm9vdDpleGFtcGxlQHRjcCgxMjcuMC4wLjE6MzMwNikvZGI/Y2hhcnNldD11dGY4bWI0JnBhcnNlVGltZT1UcnVlJmxvYz1Mb2NhbAo=  # base64-encoded username
  # password: cGFzc3dvcmQ=  # base64-encoded password
