apiVersion: v1
kind: Service
metadata:
  name: my-service-group-6
  namespace: group-6-dev
spec:
  selector:
    app: my-app-group-6
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
