apiVersion: v1
kind: Service
metadata:
  name: group-5-service2
  labels:
    app: group-5-app2
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: group-5-app2